project:
  output-dir: exports
  render:
    - "main.qmd"
  type: website

title: AML Mini-Challenge - Credit Card Affinity Modelling
author: Dominik Filliger & Noah Leuenberger (2024)

toc: true
number-sections: true

execute:
  eval: true
  echo: true

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    self-contained: true
    embed-resources: true
    code-overflow: scroll
    code-copy: hover
    fig-align: center
    fig-format: svg
    fig-responsive: true